apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: booking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-backend
  template:
    metadata:
      labels:
        app: booking-backend
    spec:
      containers:
        - name: booking-backend
          image: dgeorgijev/kiii-project-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: booking-config
            - secretRef:
                name: booking-secret