name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build backend image
        run: |
          cd booking-backend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/kiii-project-backend:latest .

      - name: Build frontend image
        run: |
          cd booking-frontend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/kiii-project-frontend:latest .

      - name: Push backend image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/kiii-project-backend:latest

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/kiii-project-frontend:latest