name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -t dgeorgijev/kiii-project-backend:latest -f booking-backend/Dockerfile .  
          docker build -t dgeorgijev/kiii-project-frontend:latest -f booking-frontend/Dockerfile . 

      - name: Push Docker images
        run: |
          docker push dgeorgijev/kiii-project-backend:latest
          docker push dgeorgijev/kiii-project-frontend:latest